version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_USER=user
     - MYSQL_PASSWORD=pass
     - MYSQL_DATABASE=test_db